// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard/CardGrid.tsx": () => import("../components/mockups/dashboard/CardGrid.tsx"),
  "./components/mockups/dashboard/Minimal.tsx": () => import("../components/mockups/dashboard/Minimal.tsx"),
  "./components/mockups/dashboard/TopNav.tsx": () => import("../components/mockups/dashboard/TopNav.tsx")
};
